import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFilesPlugin } from "./copy-files-plugin.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["index.ts"],
    bundle: true,
    external: [
        "obsidian",
        ...builtins
    ],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/index.js",
    minify: false,
    loader: {
        ".ts": "ts"
    },
    charset: 'utf8',
    legalComments: 'inline',
    keepNames: true,
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"'
    },
    plugins: [
        copyFilesPlugin([
            { from: './styles.css', to: './dist/styles.css' },
            { from: './types.d.ts', to: './dist/types.d.ts' }
        ])
    ]
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
} 